language: python
python:
  - "3.4"

install:
  - openssl aes-256-cbc -K $encrypted_8a2bdb507953_key -iv $encrypted_8a2bdb507953_iv -in travis-secrets.sh.enc -out travis-secrets.sh -d
  - chmod u+x travis-secrets.sh
  - ./travis-secrets.sh
  - pip install -r req.txt

script: ./test.sh
